[build]
publish = "public"
command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.84.3"
  NODE_VERSION = "14.17.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.84.3"
  NODE_VERSION = "14.17.0"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"