[build]
publish = "public"
command = "npm run publish"

[context.production.environment]
  HUGO_VERSION = "0.36.1"
  NODE_VERSION = "8.9.4"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.36.1"
  NODE_VERSION = "8.9.4"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

redirects = [
  {from = "/prophetic-voice-of-our-time", to = "/series/the-prophetic-voice-of-our-time/"},
  {from = "/prophetic-voice-player", to = "/series/the-prophetic-voice-of-our-time/"}
]

[[redirects]]
  from = "/prophetic-voice-of-our-time/?format=rss"
  to = "http://propheticvoice.castos.com/feed"
  status = 301
  force = true
  query = {path = ":path"} # COMMENT: apply this rule for /old-path?path=example